### ISSUE TITLE
接收数据过程中会有不定时报错，APP闪退

### ISSUE THREAD

**Issue by sweetluo** [BASS-HY/EasySerial#2]
java.nio.charset.CoderMalfunctionError: java.nio.BufferUnderflowException
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:601)
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:822)
        at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:938)
        at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:1015)
        at com.bass.easySerial.extend.EasyLoggerKt.logPortReceiveData(EasyLogger.kt:62)
        at com.bass.easySerial.wrapper.EasyKeepReceivePort$receiveData$2.invokeSuspend(EasyKeepReceivePort.kt:55)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.corouti

**Comment by sweetluo** [comment]
版本 1.0.0
